# Generated by Django 5.0.6 on 2024-09-22 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogore', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usermore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('DayOfBirth', models.CharField(blank=True, max_length=100, null=True)),
                ('Telegrame', models.URLField(blank=True, null=True)),
                ('Contrey', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('discrption', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('catogore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='News', to='api.catogores')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='News', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
                ('NewsComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.news')),
            ],
        ),
    ]
