# Generated by Django 5.0.6 on 2024-09-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='create_by',
        ),
    ]
