# Generated by Django 5.1.1 on 2024-09-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_news_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
